export const omsetProAbi = [
  {
    type: "constructor",
    inputs: [{ name: "feeRecipient_", type: "address" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "PROTOCOL_FEE_BPS",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "BPS_DENOMINATOR",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "feeRecipient",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "protocolFeeFor",
    stateMutability: "pure",
    inputs: [{ name: "amount", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "totalFundingRequired",
    stateMutability: "pure",
    inputs: [{ name: "amount", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "createAgreement",
    stateMutability: "nonpayable",
    inputs: [
      { name: "borrower", type: "address" },
      { name: "arbiter", type: "address" },
      { name: "itemName", type: "string" },
      { name: "itemMetadataURI", type: "string" },
      { name: "depositAmount", type: "uint256" },
      { name: "handoverDeadline", type: "uint64" },
      { name: "returnDeadline", type: "uint64" },
      { name: "inspectionPeriod", type: "uint64" },
      { name: "claimResponsePeriod", type: "uint64" },
    ],
    outputs: [{ name: "agreementId", type: "uint256" }],
  },
  {
    type: "function",
    name: "getAgreement",
    stateMutability: "view",
    inputs: [{ name: "agreementId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "id", type: "uint256" },
          { name: "owner", type: "address" },
          { name: "borrower", type: "address" },
          { name: "arbiter", type: "address" },
          { name: "itemName", type: "string" },
          { name: "itemMetadataURI", type: "string" },
          { name: "depositAmount", type: "uint256" },
          { name: "handoverDeadline", type: "uint64" },
          { name: "returnDeadline", type: "uint64" },
          { name: "inspectionPeriod", type: "uint64" },
          { name: "claimResponsePeriod", type: "uint64" },
          { name: "status", type: "uint8" },
          { name: "fundingTimestamp", type: "uint64" },
          { name: "handoverTimestamp", type: "uint64" },
          { name: "returnRequestTimestamp", type: "uint64" },
          { name: "claimCreationTimestamp", type: "uint64" },
          { name: "claimAmount", type: "uint256" },
          { name: "returnProofURI", type: "string" },
          { name: "claimEvidenceURI", type: "string" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "fundAgreement",
    stateMutability: "payable",
    inputs: [{ name: "agreementId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "confirmHandover",
    stateMutability: "nonpayable",
    inputs: [{ name: "agreementId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "refundUnhandedAgreement",
    stateMutability: "nonpayable",
    inputs: [{ name: "agreementId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "requestReturn",
    stateMutability: "nonpayable",
    inputs: [
      { name: "agreementId", type: "uint256" },
      { name: "returnProofURI", type: "string" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "confirmSuccessfulReturn",
    stateMutability: "nonpayable",
    inputs: [{ name: "agreementId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "finalizeUnansweredReturn",
    stateMutability: "nonpayable",
    inputs: [{ name: "agreementId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "raiseDamageClaim",
    stateMutability: "nonpayable",
    inputs: [
      { name: "agreementId", type: "uint256" },
      { name: "claimAmount", type: "uint256" },
      { name: "claimEvidenceURI", type: "string" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "raiseOverdueClaim",
    stateMutability: "nonpayable",
    inputs: [
      { name: "agreementId", type: "uint256" },
      { name: "claimAmount", type: "uint256" },
      { name: "claimEvidenceURI", type: "string" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "acceptClaim",
    stateMutability: "nonpayable",
    inputs: [{ name: "agreementId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "disputeClaim",
    stateMutability: "nonpayable",
    inputs: [{ name: "agreementId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "finalizeUnansweredClaim",
    stateMutability: "nonpayable",
    inputs: [{ name: "agreementId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "resolveDispute",
    stateMutability: "nonpayable",
    inputs: [
      { name: "agreementId", type: "uint256" },
      { name: "ownerAward", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "getOwnerAgreementIds",
    stateMutability: "view",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [{ name: "", type: "uint256[]" }],
  },
  {
    type: "function",
    name: "getBorrowerAgreementIds",
    stateMutability: "view",
    inputs: [{ name: "borrower", type: "address" }],
    outputs: [{ name: "", type: "uint256[]" }],
  },
  {
    type: "function",
    name: "getArbiterAgreementIds",
    stateMutability: "view",
    inputs: [{ name: "arbiter", type: "address" }],
    outputs: [{ name: "", type: "uint256[]" }],
  },
  {
    type: "function",
    name: "totalAgreementCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "event",
    name: "AgreementCreated",
    anonymous: false,
    inputs: [
      { name: "agreementId", type: "uint256", indexed: true },
      { name: "owner", type: "address", indexed: true },
      { name: "borrower", type: "address", indexed: true },
      { name: "arbiter", type: "address", indexed: false },
      { name: "depositAmount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "AgreementFunded",
    anonymous: false,
    inputs: [
      { name: "agreementId", type: "uint256", indexed: true },
      { name: "borrower", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "fundingTimestamp", type: "uint64", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ProtocolFeeCollected",
    anonymous: false,
    inputs: [
      { name: "agreementId", type: "uint256", indexed: true },
      { name: "payer", type: "address", indexed: true },
      { name: "feeRecipient", type: "address", indexed: true },
      { name: "feeAmount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "HandoverConfirmed",
    anonymous: false,
    inputs: [
      { name: "agreementId", type: "uint256", indexed: true },
      { name: "owner", type: "address", indexed: true },
      { name: "handoverTimestamp", type: "uint64", indexed: false },
    ],
  },
  {
    type: "event",
    name: "AgreementCancelled",
    anonymous: false,
    inputs: [
      { name: "agreementId", type: "uint256", indexed: true },
      { name: "owner", type: "address", indexed: true },
      { name: "actor", type: "address", indexed: true },
      { name: "depositRefunded", type: "bool", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ReturnRequested",
    anonymous: false,
    inputs: [
      { name: "agreementId", type: "uint256", indexed: true },
      { name: "borrower", type: "address", indexed: true },
      { name: "returnProofURI", type: "string", indexed: false },
      { name: "returnRequestTimestamp", type: "uint64", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ReturnConfirmed",
    anonymous: false,
    inputs: [
      { name: "agreementId", type: "uint256", indexed: true },
      { name: "actor", type: "address", indexed: true },
      { name: "borrower", type: "address", indexed: true },
      { name: "refundedAmount", type: "uint256", indexed: false },
      { name: "timedOut", type: "bool", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ClaimRaised",
    anonymous: false,
    inputs: [
      { name: "agreementId", type: "uint256", indexed: true },
      { name: "owner", type: "address", indexed: true },
      { name: "claimAmount", type: "uint256", indexed: false },
      { name: "claimEvidenceURI", type: "string", indexed: false },
      { name: "overdue", type: "bool", indexed: false },
      { name: "claimCreationTimestamp", type: "uint64", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ClaimDisputed",
    anonymous: false,
    inputs: [
      { name: "agreementId", type: "uint256", indexed: true },
      { name: "borrower", type: "address", indexed: true },
      { name: "arbiter", type: "address", indexed: true },
    ],
  },
  {
    type: "event",
    name: "ClaimAccepted",
    anonymous: false,
    inputs: [
      { name: "agreementId", type: "uint256", indexed: true },
      { name: "borrower", type: "address", indexed: true },
      { name: "owner", type: "address", indexed: true },
      { name: "ownerAward", type: "uint256", indexed: false },
      { name: "borrowerRefund", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ClaimFinalized",
    anonymous: false,
    inputs: [
      { name: "agreementId", type: "uint256", indexed: true },
      { name: "owner", type: "address", indexed: true },
      { name: "borrower", type: "address", indexed: true },
      { name: "ownerAward", type: "uint256", indexed: false },
      { name: "borrowerRefund", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "DisputeResolved",
    anonymous: false,
    inputs: [
      { name: "agreementId", type: "uint256", indexed: true },
      { name: "arbiter", type: "address", indexed: true },
      { name: "owner", type: "address", indexed: true },
      { name: "borrower", type: "address", indexed: false },
      { name: "ownerAward", type: "uint256", indexed: false },
      { name: "borrowerRefund", type: "uint256", indexed: false },
    ],
  },
  {
    type: "error",
    name: "AgreementNotFound",
    inputs: [{ name: "agreementId", type: "uint256" }],
  },
  { type: "error", name: "ZeroAddress", inputs: [] },
  { type: "error", name: "RolesMustBeDistinct", inputs: [] },
  { type: "error", name: "ZeroDeposit", inputs: [] },
  { type: "error", name: "InvalidHandoverDeadline", inputs: [] },
  { type: "error", name: "InvalidReturnDeadline", inputs: [] },
  { type: "error", name: "ZeroInspectionPeriod", inputs: [] },
  { type: "error", name: "ZeroClaimResponsePeriod", inputs: [] },
  { type: "error", name: "EmptyItemName", inputs: [] },
  { type: "error", name: "EmptyMetadataURI", inputs: [] },
  { type: "error", name: "EmptyReturnProofURI", inputs: [] },
  { type: "error", name: "EmptyClaimEvidenceURI", inputs: [] },
  {
    type: "error",
    name: "Unauthorized",
    inputs: [
      { name: "agreementId", type: "uint256" },
      { name: "caller", type: "address" },
    ],
  },
  {
    type: "error",
    name: "InvalidStatus",
    inputs: [
      { name: "agreementId", type: "uint256" },
      { name: "expected", type: "uint8" },
      { name: "actual", type: "uint8" },
    ],
  },
  {
    type: "error",
    name: "IncorrectDeposit",
    inputs: [
      { name: "expected", type: "uint256" },
      { name: "received", type: "uint256" },
    ],
  },
  {
    type: "error",
    name: "DeadlineExpired",
    inputs: [
      { name: "agreementId", type: "uint256" },
      { name: "deadline", type: "uint256" },
    ],
  },
  {
    type: "error",
    name: "DeadlineNotReached",
    inputs: [
      { name: "agreementId", type: "uint256" },
      { name: "deadline", type: "uint256" },
    ],
  },
  {
    type: "error",
    name: "InvalidClaimAmount",
    inputs: [
      { name: "claimAmount", type: "uint256" },
      { name: "depositAmount", type: "uint256" },
    ],
  },
  {
    type: "error",
    name: "NativeTransferFailed",
    inputs: [
      { name: "recipient", type: "address" },
      { name: "amount", type: "uint256" },
    ],
  },
] as const;
